// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKzV_GKH2fl5tofM2ESa-W2OzjCcO0wg',
    appId: '1:778581698980:web:b88556398598035a4cf931',
    messagingSenderId: '778581698980',
    projectId: 'cccc-fbd4b',
    authDomain: 'cccc-fbd4b.firebaseapp.com',
    storageBucket: 'cccc-fbd4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrMAj67pffW6wIj4-j3lXGy8ALXqZL_c',
    appId: '1:778581698980:android:3078819bbcc757264cf931',
    messagingSenderId: '778581698980',
    projectId: 'cccc-fbd4b',
    storageBucket: 'cccc-fbd4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhW9m8KdQPJUtUwkcFncXK41rjaxsQ_Hs',
    appId: '1:778581698980:ios:b077a2e6d9e2d3b74cf931',
    messagingSenderId: '778581698980',
    projectId: 'cccc-fbd4b',
    storageBucket: 'cccc-fbd4b.firebasestorage.app',
    iosBundleId: 'com.example.lab05OpenstreetmapApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhW9m8KdQPJUtUwkcFncXK41rjaxsQ_Hs',
    appId: '1:778581698980:ios:b077a2e6d9e2d3b74cf931',
    messagingSenderId: '778581698980',
    projectId: 'cccc-fbd4b',
    storageBucket: 'cccc-fbd4b.firebasestorage.app',
    iosBundleId: 'com.example.lab05OpenstreetmapApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIKzV_GKH2fl5tofM2ESa-W2OzjCcO0wg',
    appId: '1:778581698980:web:935eabe0deaabc814cf931',
    messagingSenderId: '778581698980',
    projectId: 'cccc-fbd4b',
    authDomain: 'cccc-fbd4b.firebaseapp.com',
    storageBucket: 'cccc-fbd4b.firebasestorage.app',
  );

}